#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnQF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Apply")]
	public partial class DATACONTEXT_APPLYDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DATACONTEXT_APPLYDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ApplyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DATACONTEXT_APPLYDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATACONTEXT_APPLYDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATACONTEXT_APPLYDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATACONTEXT_APPLYDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_FacturacionMensual")]
		public ISingleResult<RPT_FacturacionMensualResult> RPT_FacturacionMensual()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<RPT_FacturacionMensualResult>)(result.ReturnValue));
		}
	}
	
	public partial class RPT_FacturacionMensualResult
	{
		
		private string _CardCode;
		
		private string _CardName;
		
		private int _DocNum;
		
		private System.Nullable<System.DateTime> _DocDate;
		
		private string _ItemCode;
		
		private string _ItemName;
		
		private System.Nullable<decimal> _Quantity;
		
		private System.Nullable<decimal> _DiscPrcnt;
		
		private System.Nullable<decimal> _LineTotal;
		
		private System.Nullable<decimal> _PriceAfVAT;
		
		private System.Nullable<decimal> _GTotalSC;
		
		private System.Nullable<decimal> _GTotal;
		
		private string _SlpName;
		
		private string _GroupName;
		
		private string _Name;
		
		public RPT_FacturacionMensualResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardCode", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string CardCode
		{
			get
			{
				return this._CardCode;
			}
			set
			{
				if ((this._CardCode != value))
				{
					this._CardCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardName", DbType="NVarChar(100)")]
		public string CardName
		{
			get
			{
				return this._CardName;
			}
			set
			{
				if ((this._CardName != value))
				{
					this._CardName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocNum", DbType="Int NOT NULL")]
		public int DocNum
		{
			get
			{
				return this._DocNum;
			}
			set
			{
				if ((this._DocNum != value))
				{
					this._DocNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DocDate
		{
			get
			{
				return this._DocDate;
			}
			set
			{
				if ((this._DocDate != value))
				{
					this._DocDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="NVarChar(20)")]
		public string ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this._ItemCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(100)")]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this._ItemName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(21,6)")]
		public System.Nullable<decimal> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscPrcnt", DbType="Decimal(21,6)")]
		public System.Nullable<decimal> DiscPrcnt
		{
			get
			{
				return this._DiscPrcnt;
			}
			set
			{
				if ((this._DiscPrcnt != value))
				{
					this._DiscPrcnt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineTotal", DbType="Decimal(21,6)")]
		public System.Nullable<decimal> LineTotal
		{
			get
			{
				return this._LineTotal;
			}
			set
			{
				if ((this._LineTotal != value))
				{
					this._LineTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceAfVAT", DbType="Decimal(21,6)")]
		public System.Nullable<decimal> PriceAfVAT
		{
			get
			{
				return this._PriceAfVAT;
			}
			set
			{
				if ((this._PriceAfVAT != value))
				{
					this._PriceAfVAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GTotalSC", DbType="Decimal(21,6)")]
		public System.Nullable<decimal> GTotalSC
		{
			get
			{
				return this._GTotalSC;
			}
			set
			{
				if ((this._GTotalSC != value))
				{
					this._GTotalSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GTotal", DbType="Decimal(21,6)")]
		public System.Nullable<decimal> GTotal
		{
			get
			{
				return this._GTotal;
			}
			set
			{
				if ((this._GTotal != value))
				{
					this._GTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlpName", DbType="NVarChar(155) NOT NULL", CanBeNull=false)]
		public string SlpName
		{
			get
			{
				return this._SlpName;
			}
			set
			{
				if ((this._SlpName != value))
				{
					this._SlpName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
